import { LandingPageItem, SummaryStat, QuickAction } from "@/types/dashboard";

export const mockLandingPages: LandingPageItem[] = [
  {
    id: "lp-1",
    product: "AI Video Reels Bundle",
    slug: "ai-video-reels",
    url: "/l/ai-video-reels",
    price: "₹499",
    priceValue: 499,
    description: "Premium AI video assets, templates, and 4K viral reels resources ready for digital creators.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    status: "Published",
    createdAt: "2026-08-01",
    updatedAt: "Today",
  },
  {
    id: "lp-2",
    product: "Excel Bundle",
    slug: "excel-bundle",
    url: "/l/excel-bundle",
    price: "₹299",
    priceValue: 299,
    description: "Complete financial modeling, dashboard templates, and automated macros bundle.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    status: "Published",
    createdAt: "2026-08-10",
    updatedAt: "Yesterday",
  },
  {
    id: "lp-3",
    product: "Graphic Design Bundle",
    slug: "graphic-design",
    url: "/l/graphic-design",
    price: "₹799",
    priceValue: 799,
    description: "10,000+ vector illustrations, social media kits, typography, and PSD mockups.",
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80",
    status: "Draft",
    createdAt: "2026-08-15",
    updatedAt: "2 days ago",
  },
  {
    id: "lp-4",
    product: "Digital Marketing Course",
    slug: "digital-marketing",
    url: "/l/digital-marketing",
    price: "₹999",
    priceValue: 999,
    description: "Step-by-step masterclass on paid ads, SEO strategy, sales funnels, and email marketing.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    status: "Published",
    createdAt: "2026-08-20",
    updatedAt: "3 days ago",
  },
];

export const mockDashboardStats: SummaryStat[] = [
  {
    id: "stat-1",
    title: "Total Landing Pages",
    number: 24,
    info: "+4 this month",
    trend: "up",
  },
  {
    id: "stat-2",
    title: "Published",
    number: 18,
    info: "75% of total",
    trend: "up",
  },
  {
    id: "stat-3",
    title: "Drafts",
    number: 6,
    info: "Needs attention",
    trend: "neutral",
  },
  {
    id: "stat-4",
    title: "Total Products",
    number: 24,
    info: "All digital products",
    trend: "neutral",
  },
];

export const mockQuickActions: QuickAction[] = [
  {
    id: "qa-1",
    title: "Create Landing Page",
    description: "Create a new digital product landing page.",
    buttonText: "Create",
    href: "/admin/landing-pages/create",
  },
  {
    id: "qa-2",
    title: "Manage Landing Pages",
    description: "View and manage all your landing pages.",
    buttonText: "View Pages",
    href: "/admin/landing-pages",
  },
  {
    id: "qa-3",
    title: "Payment Pages",
    description: "Manage your payment page links.",
    buttonText: "Manage",
    href: "/admin/payment-pages",
  },
];
